
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ian
 */
public class EventView extends javax.swing.JFrame {

    /**
     * Creates new form EventView
     */
    public EventView() {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventdetailslabel1 = new javax.swing.JLabel();
        addeventlabel1 = new javax.swing.JLabel();
        colorlabel1 = new javax.swing.JLabel();
        namelabel1 = new javax.swing.JLabel();
        colorlabel2 = new javax.swing.JLabel();
        namelabel2 = new javax.swing.JLabel();
        nametxtfield = new javax.swing.JTextField();
        colorcombobox = new javax.swing.JComboBox();
        eventcombobox = new javax.swing.JComboBox();
        eventcolor = new javax.swing.JLabel();
        addevent = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(422, 355));
        getContentPane().setLayout(null);

        eventdetailslabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        eventdetailslabel1.setForeground(new java.awt.Color(255, 255, 255));
        eventdetailslabel1.setText("Event Details");
        getContentPane().add(eventdetailslabel1);
        eventdetailslabel1.setBounds(20, 10, 160, 30);

        addeventlabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        addeventlabel1.setForeground(new java.awt.Color(255, 255, 255));
        addeventlabel1.setText("Add Event");
        getContentPane().add(addeventlabel1);
        addeventlabel1.setBounds(20, 140, 130, 40);

        colorlabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        colorlabel1.setForeground(new java.awt.Color(255, 255, 255));
        colorlabel1.setText("Color");
        getContentPane().add(colorlabel1);
        colorlabel1.setBounds(30, 100, 60, 30);

        namelabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        namelabel1.setForeground(new java.awt.Color(255, 255, 255));
        namelabel1.setText("Name");
        getContentPane().add(namelabel1);
        namelabel1.setBounds(30, 50, 60, 30);

        colorlabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        colorlabel2.setForeground(new java.awt.Color(255, 255, 255));
        colorlabel2.setText("Color");
        getContentPane().add(colorlabel2);
        colorlabel2.setBounds(30, 230, 60, 30);

        namelabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        namelabel2.setForeground(new java.awt.Color(255, 255, 255));
        namelabel2.setText("Name");
        getContentPane().add(namelabel2);
        namelabel2.setBounds(30, 180, 60, 30);

        nametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(nametxtfield);
        nametxtfield.setBounds(90, 180, 280, 20);

        colorcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "White", "Green", "Yellow", "Red", "Blue", "Green" }));
        getContentPane().add(colorcombobox);
        colorcombobox.setBounds(90, 230, 110, 22);

        eventcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(eventcombobox);
        eventcombobox.setBounds(90, 50, 280, 22);

        eventcolor.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        eventcolor.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(eventcolor);
        eventcolor.setBounds(90, 100, 270, 30);

        addevent.setText("Add");
        addevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addeventActionPerformed(evt);
            }
        });
        getContentPane().add(addevent);
        addevent.setBounds(240, 230, 120, 23);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtfieldActionPerformed

    private void addeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addeventActionPerformed
        // TODO add your handling code here:
        JOptionPane.showOptionDialog(null, "Event Added!",
                  "", JOptionPane.PLAIN_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }//GEN-LAST:event_addeventActionPerformed

    private void eventcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventcomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addevent;
    private javax.swing.JLabel addeventlabel1;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox colorcombobox;
    private javax.swing.JLabel colorlabel1;
    private javax.swing.JLabel colorlabel2;
    private javax.swing.JLabel eventcolor;
    private javax.swing.JComboBox eventcombobox;
    private javax.swing.JLabel eventdetailslabel1;
    private javax.swing.JLabel namelabel1;
    private javax.swing.JLabel namelabel2;
    private javax.swing.JTextField nametxtfield;
    // End of variables declaration//GEN-END:variables
}
